### ISSUE TITLE
Is simple usage without ROS possible?

### ISSUE THREAD

**Issue by mpizenberg** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_disparity#5]
Thanks for putting this work open source.
I’m interested in trying it out for a project of mine, but if possible I’d like to avoid all the ROS things.
Do you think it would be easy to figure out how to just use the python+dnn with image pairs as input and disparity as output? without all the ROS stuff?

**Comment by gordongrigor** [comment]
Yes.  [ESS](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/isaac/models/dnn_stereo_disparity) is the DNN used for this package and can run outside of ROS via TensorRT, provided it has the correct pre-processing, and rectified stereo camera pairs.

**Comment by mpizenberg** [comment]
Thanks! I ended up on that page but unfortunately could not figure out how to decrypt the `.etlt` model. It seems Nvidia does not provide a `tao-converter` executable for windows. And even in my linux (archlinux) I could not execute it. It just says the following:

```txt
./tao-converter -h
exec: Failed to execute process: '/home/matthieu/temp/nvidia-ess/bin/tao-converter' the file could not be run by the operating system.
```
I’m a bit disheartened to find out how complex it is to use learning models these days.

**Comment by gordongrigor** [comment]
The .etlt model needs to be processed to run on the target GPU for inference.  The Isaac ROS instructions for this are on [using-tao-converter-to-decrypt-the-encrypted-tlt-model-etlt-format](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference/blob/main/docs/model-preparation.md#using-tao-converter-to-decrypt-the-encrypted-tlt-model-etlt-format).  Thanks.

**Comment by mpizenberg** [comment]
I’ve figured it out, now have a simple setup with one two-staged `Dockerfile`, a `docker-compose.yml` file, and an `src/nvidia-ess-script.ipnb` notebook. Unfortunately I can’t share it here. The gist of it is the first stage of the dockerfile converts the `ess.etlt` file into the `ess.engine` for your architecture, and the second stage adds some stuff for the code in the notebook to run (numpy, jupyter, ...). The `docker-compose.yml` file contains two services, a `builder` stage that uses the first stage of the docker file, and a `runner` service that setup everything for you to just have to start jupyter inside the docker.

The docker compose file is very convenient since it has the volumes, network and gpu setup already configured. The content of the notebook is inspired from a[ TensorRT tutorial for semantic segmentation](https://github.com/NVIDIA/TensorRT/blob/d7baf010e4396c87d58e4d8a33052c01c2d89325/quickstart/SemanticSegmentation/tutorial-runtime.ipynb) but adapted to this model.

That’s basically it. I can’t share the code but I can share the readme in case it also helps people reproducing my setup, so here it is.

-------------


# Disparity maps with deep learning (nvidia ess)

This repository contains a container ready to use to compute disparity maps with the [Nvidia ESS model][nvidia-ess].
The ESS model estimates disparity for a stereo image pair and returns a continuous disparity map for the given left image.
It was made public in June 2022 and is one of the most precise DL model for disparity maps.

[nvidia-ess]: https://catalog.ngc.nvidia.com/orgs/nvidia/teams/isaac/models/dnn_stereo_disparity

## Requirements

You need a computer with a cuda-capable GPU, and to have installed already the Nvidia and Cuda drivers on your machine.
You also need to have Docker installed, and setup such that it is capable to access the nvidia GPU.
All the rest is dealt with directly inside the Docker containers I’ve setup for this task.
You also need a lot of space of your machine.
The containers with nvidia drivers and full python install with numpy and others, will typically take 10GB to 20GB of your disk.

## Preparing the containers

Nvidia provides a pre-trained model which is encrypted and only usable with the TensorRT platform.
This encrypted model must be converted to a TensorRT engine file, tailor-made for YOUR computer.
As such, the container is split in two stages:
 - The builder stage, downloading the encrypted `ess.etlt` file, and generating the `models/ess.engine` trt model for your machine.
 - The runner stage, which contains a jupyter notebook enabling you to run the model on your images.

A `docker-compose.yml` file is provided and preconfigured to start each stage with the correct options (GPU, volumes, network, ...).
First, we need to build the containers.
Open a terminal in this directory and execute the following command.

```sh
docker compose build
```

This will download and prepare both the builder dn runner stages of the containers.
Now we need to convert the encrypted `ess.etlt` file (stored inside the builder container) into the `ess.engine` trt model for your machine.
This is done by runing the fist docker stage.

```sh
docker compose run --rm builder
```

If all went well, it should have generated the file `models/ess.engine` that we will be able to use in the next stage.

```sh
docker compose run --rm --service-ports runner
```

This second step generate and starts the runner container.
You should now be in a prompt inside the container, ready for the next step: computing disparity maps.

## Computing disparity maps

I’ve setup a jupyter notebook inside the `src/` directory of this repository.
Once you have started the runner stage of the container and you are in its prompt, it’s time to start jupyter.
Run the following command, still from your current directory in the container, which should be `/home`.

```sh
jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root
```

This will have started jupyter and provided you with a link that should start with
`http://127.0.0.1:8888/?token=...`.
Open this link in your browser, and open the `src/nvidia-ess-script.ipynb` notebook.
From there, you simply have to execute all the cells, and replace the default images with yours in the last few cells.
That’s all!
