### ISSUE TITLE
Converting .engine file with int8 instead of fp16

### ISSUE THREAD

**Issue by chen-harrison** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_stereo_disparity#6]
I am running on Jetpack 5.0.2 on Jetson Xavier NX, and after running some initial tests with the .engine model output from the tao-converter command, I was getting inference time in the realm of 0.1 seconds on average. In hopes of achieving real-time performance (ideally around 30fps), I modified the tao-converter command to use int8 instead fp16. However, upon doing so, I received the error
```
[ERROR] 1: Unexpected exception _Map_base::at
[ERROR] Unable to create engine
Segmentation fault (core dumped)
```
The command I am running just modifies the original from `-t fp16` to `-t int8`, so something like
```
/opt/nvidia/tao/tao-converter -k ess -t int8 -e /workspaces/isaac_ros-dev/src/isaac_ros_dnn_stereo_disparity/resources/ess.engine -o output_left /workspaces/isaac_ros-dev/src/isaac_ros_dnn_stereo_disparity/resources/ess.etlt
```

Do you have any insight on what might be causing the error?

Also, along the lines of sped up performance, is there any way to modify the input dimensions (i.e. reducing them)? It seems the network resizes the input image to 960x576 prior to inference, such that downsizing the input image provides no perceptible gains in inference time.

Thanks in advance!

**Comment by jaiveersinghNV** [comment]
We are looking into why conversion to `int8` is causing problems.

As for resizing the input dimensions, the ESS model has been trained specifically on the 960x576 resolution and so downsizing the input image will not have any effect.

**Comment by gordongrigor** [comment]
ESS is a custom DNN which is not supported for INT8 conversion from FP16 in TAO.  To achieve great accuracy in INT8 the pre-trained ESS model would need to designed for INT8 and use quantization aware training.

ESS is has been heavily optimized to achieve ~30fps on Jetson AGX Xavier at 1/4 HD resolution and will continue to work on improving performance of this network.
